AppBundle\Entity\Image:
    type: entity
    table: image
    indexes:
        img2user:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        source:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        voteCount:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: vote_count
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
